name: Nginx CI

on:
  push:
    branches:
      - main

    paths:
      - 'infrastructure/nginx/**'
      - '.github/workflows/nginx-ci.yml'

  workflow_dispatch:

jobs:
  nginx:
    name: Validate Nginx
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Nginx image
        run: >
          docker build
          -t piscinapp-nginx:ci
          ./infrastructure/nginx

      - name: Validate Nginx configuration
        run: >
          docker run
          --rm
          --add-host core:127.0.0.1
          piscinapp-nginx:ci
          nginx -t
